version: '2'

services:
  # Requires having a build in ./topurls-service/target/scala-2.11/topurls-service_2.11-0.1-SNAPSHOT.jar
  topurls-service:
    image: gettyimages/spark
    environment:
      DEBUG_ENV: "true"
    depends_on:
      - elasticsearch
      - zookeeper
      - kafka
    volumes:
      - ./topurls-service:/topurls-service
    command: "/topurls-service/deploy-local.sh"

  # Requires having a build in ./aggregation-service/target/scala-2.11/aggregation-test_2.11-0.1-SNAPSHOT.jar
  aggregation-service:
    image: gettyimages/spark
    environment:
      DEBUG_ENV: "true"
    depends_on:
      - mongo
      - zookeeper
      - kafka
    volumes:
      - ./aggregation-service:/aggregation-service
    command: "/aggregation-service/deploy-local.sh"

  # Requires having a build in ./blacklisted-traffic-service/target/scala-2.11/topurls-service_2.11-0.1-SNAPSHOT.jar
  blacklisted-traffic-service:
    image: gettyimages/spark
    environment:
      DEBUG_ENV: "true"
    depends_on:
      - elasticsearch
      - zookeeper
      - kafka
    volumes:
      - ./blacklisted-traffic-service:/blacklisted-traffic-service
    command: "/blacklisted-traffic-service/deploy-local.sh"

  # Requires having a build in ./adserver-report-extraction-task/job/target/scala-2.11/report-importer_2.11-1.0.jar
  adserver-report-extraction-task:
    build: ./adserver-report-extraction-task/job/.
    environment:
      SEEDTAG_API_KEY: e947f68afb0371afe92acf3fbcc541e31f0506b878ea765de51bea322ae8b56a6fb5e9efaa5236416fa14c6e27233e7c
    depends_on:
      - mongo
      - tag-manager-service
      - user-service
    volumes:
      - ./adserver-report-extraction-task:/adserver-report-extraction-task
    # By default do nothing, just run the container to do whatever you want in a shell
    command: "tail -f /dev/null"
    # If you want to run the job:
    # command: ./deploy-local.sh <CsvFilePath>
    # If you want to pass the tests
    # command: "sbt test"
