mongo:
  image: mongo:2.6
  command: "--smallfiles"
  expose:
      - "27017"
  ports:
      - "27017:27017"

user-service:
  build: ./user-service
  ports:
      - "3040:3040"
      - "3041:3041"
      - "3042:3042"
  links:
      - email-service
      - mongo
  volumes:
      - ./user-service:/code
      - /code/node_modules
  command: bash -c "npm run dev"
  environment:
      PUBLIC_SIGNING_KEY: "-----BEGIN RSA PUBLIC KEY-----\nMIIBCgKCAQEAlzeoxJWykxYJFVv4RnDtfooC9K3dXPWClQ/UER+z7Evg9RzwQc1W\nzsXkYc4R1SIKE1edy6SQNzlFZAcTnz+ICAlT7TcnCaA2VUU9z7W29d/He+e3Y4nw\n7uJOH1DUfgU7K1gZn/Abndk7GnDIJjXuBfaLQCDiKqDqcFNM+3f3Ir2u9gTOZALP\nQgDwZiWKiyj0V9gZEQcxOJA14vNARboMiewE63BhiDiBoU5HK7zw/ZgeXWJ8TSRg\nbe6YRsYSdmf1DL17AVxPxW9LHEKW4w4suDHcaLDOajORBGYqJc3FodvJvZSwg2N3\ngvaMukeh7j0nTJYlnXgddPaIxn64J5LghQIDAQAB\n-----END RSA PUBLIC KEY-----"
      PRIVATE_SIGNING_KEY: "-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEAlzeoxJWykxYJFVv4RnDtfooC9K3dXPWClQ/UER+z7Evg9Rzw\nQc1WzsXkYc4R1SIKE1edy6SQNzlFZAcTnz+ICAlT7TcnCaA2VUU9z7W29d/He+e3\nY4nw7uJOH1DUfgU7K1gZn/Abndk7GnDIJjXuBfaLQCDiKqDqcFNM+3f3Ir2u9gTO\nZALPQgDwZiWKiyj0V9gZEQcxOJA14vNARboMiewE63BhiDiBoU5HK7zw/ZgeXWJ8\nTSRgbe6YRsYSdmf1DL17AVxPxW9LHEKW4w4suDHcaLDOajORBGYqJc3FodvJvZSw\ng2N3gvaMukeh7j0nTJYlnXgddPaIxn64J5LghQIDAQABAoIBAFudszh3YdvPa+1u\n7TrwTFNwFl5bwFQDwvvAvUEqrf2p8z9OKxoS6FcaekXvbcptdyFE4itxJpbuseXq\ni67d9PK5hAmicppYYNLEwrBHbfQFgnzFZMx/1GNG5QIAHN3FGZYnKE9IT9MQu8hH\nMFxGLFGcj71ort4Y5DDtpyRsCGUZDLBN45IFLP5oRhaKDFSWD4exev8GeQDpJkgK\nsb6w1n0KJLqShvvM8SMkNsKLnxT9jgz5o3PK5wjPIS1q+bxJH4edIi37sOtrnCak\n6E2Qh/ZpRMnyKS9MYjFGLoSESKrojBoRWqat6ygQKheep82wZRKsRNptov7YlQ8t\nJOsI6PkCgYEAxPx6esAE1EnLpPupRgf5ki9zH8t5JDYlAPOQpHDZKvLZCB35D5O3\n+8FLCju190g5AC0jwgbcr6d7CvPrSfVH8w3e+gv0dyuUysoXBG0ZuWtKYc/SVZ2e\niN/qp/5leRpV2wQzK6mSBTrrs55ykHPSpBarpUHpR7W1/e83T6uyi9MCgYEAxIUE\n+EGCiDi9BZXja5RbwOxPp3oUKAPcrFH1n5nNwCrr7kP8ncY11JJC5nKLtCm624gt\nMB+h0dbaO7WGQ29gVABpiVvbAOckMpo+xC4S8xgus6/4aKvYWIffe6M3x/nuQfS5\n6HMsC9HT0zeaUsm7BcoES0Pueq5Zi8INhdtm40cCgYAqi8m8d3rTizjT4pM2EATk\ngSEhbeY1XwhxAyprigAt2ZPsv+SKa8JiOuaFSE5OIahGFHnTr3285rSZsgNQzwyC\nP624XhqoHp6dijaceyACP10qcSOh4FBcidh5/mVWWczPaEHRHWfvf0FnY0KlVo7Z\naBgcsna7SVEMjr1olNIUhwKBgCjH8eASuCPMom0mTatlfiTq5Ry8GLK1GnYoC/Cy\n2h+myI8JTMLw/vq932QzIQqiHkSwXbA+4DXLgD4jzVjxI+xKqZv3k9r8HGbj22Ka\nrRQFUKu5OLN/9cVpbNcbZ9f35ZmKT4oNXHaXdH3AbCYB9u2cnod/8V1EEREPk/7T\nKObBAoGBAI2xZOE2SFqjS4IoTFinJkGr/WjnP13vyoQPfIqThQCawv2KAaSfD4Lv\nS/r+6dYXU6oteol1bSLMmkXN4lWBxgpqAC+Gbvv982SgEq6+WdbI1IpPnqtbC8F4\nH3s8bB3nKjE1KA8UXzavsQa9tbel3SO/wQhMVTBvml52+ieAhK0w\n-----END RSA PRIVATE KEY-----"
      MAIN_DATABASE_SERVICE_HOST: "mongo"
      MAIN_DATABASE_SERVICE_PORT: "27017"
      SEEDTAG_TLD: ".seedtag.local" # ".seedtag.com" in production
      SEEDTAG_JWT_COOKIE_NOT_SECURE: 'true' # Should not be defined in production
      NODE_ENV: 'development'

studio-service:
  build: ./studio/server
  expose:
    - "3010"
  environment:
      PUBLIC_SIGNING_KEY: "-----BEGIN RSA PUBLIC KEY-----\nMIIBCgKCAQEAlzeoxJWykxYJFVv4RnDtfooC9K3dXPWClQ/UER+z7Evg9RzwQc1W\nzsXkYc4R1SIKE1edy6SQNzlFZAcTnz+ICAlT7TcnCaA2VUU9z7W29d/He+e3Y4nw\n7uJOH1DUfgU7K1gZn/Abndk7GnDIJjXuBfaLQCDiKqDqcFNM+3f3Ir2u9gTOZALP\nQgDwZiWKiyj0V9gZEQcxOJA14vNARboMiewE63BhiDiBoU5HK7zw/ZgeXWJ8TSRg\nbe6YRsYSdmf1DL17AVxPxW9LHEKW4w4suDHcaLDOajORBGYqJc3FodvJvZSwg2N3\ngvaMukeh7j0nTJYlnXgddPaIxn64J5LghQIDAQAB\n-----END RSA PUBLIC KEY-----"
  links:
      - email-service
  volumes:
    - ./studio/server/src:/code/src
    - ./studio/server/src/template/lib:/template_lib
    - ./studio/creatives:/creatives
  command: npm run dev
  environment:
      PUBLIC_SIGNING_KEY: "-----BEGIN RSA PUBLIC KEY-----\nMIIBCgKCAQEAlzeoxJWykxYJFVv4RnDtfooC9K3dXPWClQ/UER+z7Evg9RzwQc1W\nzsXkYc4R1SIKE1edy6SQNzlFZAcTnz+ICAlT7TcnCaA2VUU9z7W29d/He+e3Y4nw\n7uJOH1DUfgU7K1gZn/Abndk7GnDIJjXuBfaLQCDiKqDqcFNM+3f3Ir2u9gTOZALP\nQgDwZiWKiyj0V9gZEQcxOJA14vNARboMiewE63BhiDiBoU5HK7zw/ZgeXWJ8TSRg\nbe6YRsYSdmf1DL17AVxPxW9LHEKW4w4suDHcaLDOajORBGYqJc3FodvJvZSwg2N3\ngvaMukeh7j0nTJYlnXgddPaIxn64J5LghQIDAQAB\n-----END RSA PUBLIC KEY-----"


studio-client:
  build: ./studio/client
  volumes:
    - ./studio/client/src:/code/src
  ports:
    - "3003:3003"
  command: bash -c "npm run server:dev"

email-service:
  build: ./email-service
  ports:
      - "3020:3020"
  links:
      - mongo
  volumes:
      - ./email-service:/code
      - /code/node_modules
  command: bash -c "npm run dev"
  environment:
      MAIN_DATABASE_SERVICE_HOST: "mongo"
      MAIN_DATABASE_SERVICE_PORT: "27017"
      NODE_ENV: 'development'
      # Mailgun credentials must be defined in your local env
      MAILGUN_DOMAIN:
      MAILGUN_API_KEY:

nginx:
    build: ./nginx
    ports:
        - "80:80"
    links:
        - user-service
        - studio-client
        - studio-service
    volumes:
        - ./nginx/conf:/etc/nginx

sherlock-service:
  build: ./sherlock-service
  volumes:
    - ./sherlock-service:/code
  environment:
    MAIN_DATABASE_SERVICE_HOST: "mongo"
    MAIN_DATABASE_SERVICE_PORT: "27017"
    NODE_ENV: 'development'
  command: npm run dev
