  version: '2'

  services:
    studio:
      build: ./studio/client
      volumes:
        - ./studio/client/src:/code/src
      ports:
        - "3050:3000"
      environment:
        NODE_ENV: "development"
      command: npm run start

    backoffice:
      build: ./backoffice
      volumes:
        - ./backoffice:/code
        - /code/node_modules
      ports:
        - "3060:3000"
      command: yarn start

    publisher-panel:
      build: ./publisher-panel
      volumes:
        - ./publisher-panel:/code
        - /code/node_modules
      ports:
        - "3090:3000"
      command: yarn start

    gohan:
      build: ./gohan/packages/client
      volumes:
        - ./gohan/packages/client:/code
        - ./gohan/packages/client/node_modules:/code/node_modules
      ports:
        - "8886:8886"
      command: npm run start
